name: release

on: [ push, pull_request ]

jobs:
  release:
    runs-on: ubuntu-latest
    needs: build-and-test
    # Only create a Release if it was a push to main
    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: Output

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Create Github Release
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nightly-${{ steps.date.outputs.date }}.${{ github.run_number }}
          release_name: nightly-${{ steps.date.outputs.date }}.${{ github.run_number }}

      - name: Upload asset to Github Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: ./${{ github.event.repository.name }}.jar
          asset_name: ${{ github.event.repository.name }}.jar
          asset_content_type: application/jar

  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'

      - name: Cache Spigot and gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/
            ~/.gradle/caches/
            ~/.gradle/wrapper/
            ./BuildTools/
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup Spigot with BuildTools
        run: mkdir BuildTools -p && cd BuildTools && wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar -O BuildTools.jar && java -jar BuildTools.jar --rev 1.17.1 --compile-if-changed && cd ..

      - name: Setup gradlew permissions
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew -Pversion="nightly-${{ steps.date.outputs.date }}.${{ github.run_number }}" -PpluginName="${{ github.event.repository.name }}" build

      - name: Cleanup Gradle Cache
        # Remove some files from the Gradle cache, so they aren't cached by GitHub Actions.
        # Restoring these files from a GitHub Actions cache might cause problems for future builds.
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Output
          path: build/libs/
